import Header from "@/components/main/Header";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose what you need
  variable: "--font-roboto",
  display: "swap",
});

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-bricolage",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body
    className={`min-h-screen w-full relative dark:bg-black ${bricolage.variable} ${geistSans.variable} ${geistMono.variable} font-bricolage antialiased`}
  >
    <div
      className={`
        absolute inset-0 z-0 
        [background:radial-gradient(125%_125%_at_50%_90%,#fff_40%,#6366f1_100%)]
        dark:[background:radial-gradient(ellipse_80%_60%_at_50%_0%,rgba(139,92,246,0.25),transparent_70%),#000]
      `}
    >
      <Header />
      {children}
    </div>
  </body>
</html>

  );
}
